version: "3.8"

services:
  backend:
    build: .
    container_name: traffic-sign-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: traffic-sign-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
  
  uploader:
    build: ./scripts
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
    networks:
      - app-network
    restart: "no"

networks:
  app-network:
    driver: bridge
